### ISSUE TITLE
integration with nvim-treesitter

### ISSUE THREAD

**Issue by nat-418** [lewis6991/tree-sitter-tcl#4]
What needs to be done to get this integrate into nvim-treesitter?

**Comment by lewis6991** [comment]
Nothing. nvim-treesitter is not needed. Just install this as a normal plugin.

**Comment by nat-418** [comment]
Ok, sorry about my confusion. Is there anyway I can get this plugin to show up in e.g., `:TSModuleInfo` ?

**Comment by lewis6991** [comment]
No

**Comment by nat-418** [comment]
Ok. So what do I need to do to get your work integrated with treesitter-context, search and replace,etc?
